steps:
  - id: test
    name: golang:1.13
    entrypoint: make
    args: ['test']

  - id: build
    name: golang:1.13
    entrypoint: make
    args: ['build']

  - id: compress
    name: golang:1.13
    entrypoint: make
    args: ['compress']

  - id: publish
    name: buildkite/github-release:latest
    env:
    - GITHUB_RELEASE_REPOSITORY=sethvargo/vault-auth-slack
    - GITHUB_RELEASE_COMMIT=$COMMIT_SHA
    - GITHUB_RELEASE_TAG=$TAG_NAME
    secretEnv:
    - GITHUB_RELEASE_ACCESS_TOKEN
    args:
    - $TAG_NAME
    - build/darwin_amd64.tgz
    - build/linux_amd64.tgz
    - build/windows_amd64.tgz

secrets:
- kmsKeyName: projects/sethvargo-cicd/locations/global/keyRings/vault-auth-slack/cryptoKeys/github-token
  secretEnv:
    GITHUB_RELEASE_ACCESS_TOKEN: CiQAtN6cKSOHtR0T4CfPMrmYUYC1D2TNvCO2OaEnqFjnCqvVncwSUQADnOsXxTogG4rqXJ7iOVAFgn9RwDxCpj9qAnuH81y1YzroIlw8F7pVhmu0yIwl3HI5DYX7ik2A82s+fQC1qm+BeeaXNOy1BXbWmGyBPGEHJA==

options:
  machineType: N1_HIGHCPU_8
